const express = require("express");
const app = express();

app.set('view engine', 'ejs');
app.use("/public", express.static(__dirname + "/public"));
app.use(express.urlencoded({ extended: true }));

let character = [
    { id:1 , number:"DBL07-11S" , name:"破壊神 ビルス" , color:"GRN" , tag:"破壊神" , tag:"神の気" , tag:"双子" , tag:"強大な敵" } ,
    { id:2 , number:"DBL10-06S" , name:"超サイヤ人2 孫悟飯:少年期" , color:"RED" , tag:"混血サイヤ人" , tag:"孫一族" , tag:"超サイヤ人2" } ,
    { id:3 , number:"DBL12-06S" , name:"超サイヤ人 孫悟天：幼年期" , color:"PUR" , tag:"混血サイヤ人", tag:"孫一族" , tag:"超サイヤ人" , tag:"キッズ" } ,
    { id:4 , number:"DBL13-03S" , name:"超ベジット" , color:"PUR" , tag:"サイヤ人" , tag:"超サイヤ人" , tag:"合体戦士" , tag:"ポタラ" } ,
    { id:5 , number:"DBL15-05S" , name:"孫悟空" , color:"BLU" , tag:"サイヤ人" , tag:"孫一族" } ,
    { id:6 , number:"DBL17-05S" , name:"超サイヤ人3 孫悟空" , color:"GRN" , tag:"サイヤ人" , tag:"超サイヤ人3" , tag:"孫一族" } ,
    { id:7 , number:"DBL18-05S" , name:"超サイヤ人ゴッドSS ベジータ" , color:"GRN" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"未来" } ,
    { id:8 , number:"DBL22-03S" , name:"ピッコロ" , color:"YEL" , tag:"再生" , tag:"ナメック星人" } ,
    { id:9 , number:"DBL22-05S" , name:"第一形態 フリーザ" , color:"PUR" , tag:"フリーザ軍" , tag:"変身戦士" , tag:"悪の系譜" , tag:"強大な敵" } ,
    { id:10 , number:"DBL24-01S" , name:"超サイヤ人ゴッドSS ベジット" , color:"BLU" , tag:"サイヤ人" , tag:"超サイヤ人ゴッドSS" , tag:"神の気" , tag:"未来" , tag:"合体戦士" } ,
    { id:11 , number:"DBL26-06S" , name:"ベジータ" , color:"BLU" , tag:"サイヤ人" , tag:"ベジータ一族" } ,
    { id:12 , number:"DBL29-04S" , name:"身勝手の極意\"兆し\" 孫悟空" , color:"PUR" , tag:"サイヤ人" , tag:"孫一族" , tag:"神の気" , tag:"宇宙代表" } ,
    { id:13 , number:"DBL30-01S" , name:"超サイヤ人ゴッドSS ゴジータ" , color:"YEL" , tag:"サイヤ人" , tag:"超サイヤ人ゴッドSS" , tag:"合体戦士" , tag:"神の気" , tag:"フュージョン" } ,
    { id:14 , number:"DBL30-03S" , name:"超サイヤ人 ブロリー" , color:"BLU" , tag:"サイヤ人" , tag:"超サイヤ人" , tag:"強大な敵" } ,
    { id:15 , number:"DBL31-01S" , name:"超サイヤ人 孫悟飯" , color:"YEL" , tag:"混血サイヤ人" , tag:"孫一族" , tag:"超サイヤ人" , tag:"未来" } ,
    { id:16 , number:"DBL32-02S" , name:"魔人ブウ：純粋" , color:"BLU" , tag:"吸収" , tag:"再生" , tag:"強大な敵" } ,
    { id:17 , number:"DBL33-02S" , name:"超サイヤ人ロゼ ゴクウブラック" , color:"PUR" , tag:"サイヤ人" , tag:"未来" , tag:"神の気" , tag:"超サイヤ人ロゼ" , tag:"強大な敵" } ,
    { id:18 , number:"DBL34-01S" , name:"超サイヤ人4 孫悟空" , color:"YEL" , tag:"サイヤ人" , tag:"孫一族" , tag:"GT" , tag:"超サイヤ人4" } ,
    { id:19 , number:"DBL35-01S" , name:"超サイヤ人4 ゴジータ" , color:"GRN" , tag:"サイヤ人" , tag:"超サイヤ人4" , tag:"合体戦士" , tag:"GT" , tag:"フュージョン" } ,
    { id:20 , number:"DBL35-08S" , name:"半身崩壊 合体ザマス" , color:"RED" , tag:"神の気" , tag:"未来" , tag:"再生" , tag:"合体戦士" , tag:"ポタラ" , tag:"強大な敵" } ,
    { id:21 , number:"DBL36-01S" , name:"超サイヤ人 孫悟飯：少年期" , color:"PUR" , tag:"混血サイヤ人" , tag:"孫一族" , tag:"超サイヤ人" } ,
    { id:22 , number:"DBL37-02S" , name:"最終形態 フリーザ：フルパワー" , color:"YEL" , tag:"フリーザ軍" , tag:"変身戦士" , tag:"悪の系譜" , tag:"強大な敵" } ,
    { id:23 , number:"DB38L-01S" , name:"超サイヤ人ゴッドSS：進化 ベジータ" , color:"YEL" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"宇宙代表" } ,
    { id:24 , number:"DBL39-01S" , name:"ベジータ" , color:"RED" , tag:"フリーザ軍" , tag:"サイヤ人" , tag:"強大な敵" , tag:"ベジータ一族" } ,
    { id:25 , number:"DBL40-02S" , name:"パーフェクトセル" , color:"PUR" , tag:"人造人間" , tag:"吸収" , tag:"再生" , tag:"未来" , tag:"強大な敵" } ,
    { id:26 , number:"DBL41-01S" , name:"超サイヤ人ゴッドSS 孫悟空＆ベジータ" , color:"PUR" , tag:"サイヤ人" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"孫一族" , tag:"ベジータ一族" } ,
    { id:27 , number:"DBL41-02S" , name:"超サイヤ人 トランクス：青年期" , color:"BLU" , tag:"混血サイヤ人" , tag:"超サイヤ人" , tag:"未来" , tag:"ベジータ一族" , tag:",武器持ち" } ,
    { id:28 , number:"DBL43-01S" , name:"バーダック" , color:"YEL" , tag:"サイヤ人" , tag:"バーダックチーム" } ,
    { id:29 , number:"DBL44-01S" , name:"ジレン：フルパワー" , color:"PUR" , tag:"ライバル宇宙" , tag:"第11宇宙" , tag:"強大な敵" , tag:"宇宙代表" } ,
    { id:30 , number:"DBL46-01S" , name:"人造人間17号＆人造人間18号" , color:"RED" , tag:"人造人間" , tag:"ガールズ" , tag:"双子" , tag:"未来" , "強大な敵" } ,
    { id:31 , number:"DBL47-01S" , name:"身勝手の極意 孫悟空" , color:"RED" , tag:"サイヤ人" , tag:"孫一族" , tag:"神の気" , tag:"宇宙代表" } ,
    { id:32 , number:"DBL48-01S" , name:"超サイヤ人3 孫悟空" , color:"GRN" , tag:"サイヤ人" , tag:"超サイヤ人3" , tag:"孫一族" } ,
    { id:33 , number:"DBL50-01S" , name:"超サイヤ人 トランクス：青年期" , color:"GRN" , tag:"混血サイヤ人" , tag:"ベジータ一族" , tag:"超サイヤ人" , tag:"未来" , tag:"武器持ち" } ,
    { id:34 , number:"DBL51-01S" , name:"最終形態 クウラ" , color:"RED" , tag:"変身戦士" , tag:"悪の系譜" , tag:"強大な敵" } ,
    { id:35 , number:"DBL52-01S" , name:"ビースト 孫悟飯" , color:"BLU" , tag:"混血サイヤ人" , tag:"孫一族" } ,
    { id:36 , number:"DBL53-01S" , name:"超サイヤ人4 孫悟空＆ベジータ" , color:"GRN" , tag:"サイヤ人" , tag:"GT" , tag:"超サイヤ人4" , tag:"孫一族" , tag:"ベジータ一族" } ,
    { id:37 , number:"DBL54-03S" , name:"超サイヤ人2＆超サイヤ人ゴッドSS トランクス：青年期＆ベジータ" , color:"YEL" , tag:"ベジータ一族" , tag:"混血サイヤ人" , tag:"未来" , tag:"超サイヤ人2" , tag:"武器持ち" , tag:"サイヤ人" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" } ,
    { id:38 , number:"DBL55-01S" , name:"人造人間17号" , color:"BLU" , tag:"人造人間" , tag:"双子" , tag:"宇宙代表" } ,
    { id:39 , number:"DBL56-01S" , name:"超サイヤ人ゴッドSS 孫悟空" , color:"GRN" , tag:"サイヤ人" , tag:"孫一族" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"宇宙代表" } ,
    { id:40 , number:"DBL58-01S" , name:"超サイヤ人3＆超サイヤ人2 孫悟空＆ベジータ" , color:"BLU" , tag:"サイヤ人" , tag:"超サイヤ人3" , tag:"孫一族" , tag:"超サイヤ人2" , tag:"ベジータ一族" , tag:"あの世の戦士" } ,
    { id:41 , number:"DBL59-01S" , name:"孫悟空＆最終形態フリーザ" , color:"PUR＆BLU" , tag:"サイヤ人" , tag:"孫一族" , tag:"宇宙代表" , tag:"フリーザ軍" , tag:"変身戦士" , tag:"悪の系譜" , tag:"あの世の戦士" } ,
    { id:42 , number:"DBL60-02S" , name:"潜在能力解放 ピッコロ" , color:"GRN" , tag:"再生" , tag:"融合" , tag:"超戦士" , tag:"ナメック星人" , tag:"変身戦士" } ,
    { id:43 , number:"DBL60-03S" , name:"ガンマ1号＆ガンマ2号" , color:"YEL" , tag:"人造人間" , tag:"武器持ち" } ,
    { id:44 , number:"DBL61-03S" , name:"完全体 セル" , color:"PUR" , tag:"人造人間" , tag:"吸収" , tag:"再生" , tag:"未来" , tag:"強大な敵" } ,
    { id:45 , number:"DBL62-04S" , name:"超サイヤ人 孫悟空" , color:"BLU" , tag:"サイヤ人" , tag:"超サイヤ人" , tag:"孫一族" } ,
    { id:46 , number:"DBL63-01S" , name:"孫悟空：少年期" , color:"PUR" , tag:"サイヤ人" , tag:"キッズ" , tag:"孫一族" , tag:"孫一族" , tag:"DB" , tag:"武器持ち" } ,
    { id:47 , number:"DBL64-02S" , name:"パイクーハン" , color:"GRN" , tag:"あの世の戦士" , tag:"サイヤ人" , tag:"超サイヤ人" , tag:"合体戦士" , tag:"フュージョン" } ,
    { id:48 , number:"DBL65-01S" , name:"超サイヤ人ゴッドSS：進化＆超サイヤ人ゴッド界王拳 ベジータ＆孫悟空" , color:"GRN" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"宇宙代表" , tag:"孫一族" } ,
    { id:49 , number:"DBL65-02S" , name:"アルティメット孫悟飯" , color:"RED" , tag:"混血サイヤ人" , tag:"孫一族" } ,
    { id:50 , number:"DBL66-01S" , name:"孫悟空＆バーダック" , color:"BLU＆GRN" , tag:"サイヤ人" , tag:"孫一族" , tag:"バーダックチーム" } ,
    { id:51 , number:"DBL67-01S" , name:"孫悟空" , color:"BLU" , tag:"サイヤ人" , tag:"孫一族" , tag:"GT" , tag:"キッズ" } ,
    { id:52 , number:"DBL67-05S" , name:"超17号" , color:"RED" , tag:"人造人間" , tag:"融合" , tag:"合体戦士" , tag:"GT" , tag:"強大な敵" } ,
    { id:53 , number:"DBL68-01S" , name:"超ベジータ" , color:"RED" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"超サイヤ人" } ,
    { id:54 , number:"DBL69-01S" , name:"スーパーベビー2" , color:"YEL" , tag:"融合" , tag:"GT" , tag:"変身戦士" , tag:"再生" , tag:"サイヤ人" , tag:"強大な敵" } ,
    { id:55 , number:"DBL70-03S" , name:"ナッパ" , color:"PUR" , tag:"フリーザ軍" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"強大な敵" } ,
    { id:56 , number:"DBL71-01S" , name:"ベジータ＆孫悟空" , color:"BLU" , tag:"サイヤ人" , tag:"ベジータ一族" , tag:"あの世の戦士" , tag:"孫一族" , tag:"超サイヤ人" , tag:"合体戦士" , tag:"ポタラ" } ,
    { id:57 , number:"DBL71-02S" , name:"超サイヤ人ゴッドSS 孫悟空＆ベジータ" , color:"YEL" , tag:"サイヤ人" , tag:"孫一族" , tag:"神の気" , tag:"超サイヤ人ゴッドSS" , tag:"ベジータ一族" , tag:"合体戦士" , tag:"フュージョン" } ,
    { id:58 , number:"DBL72-01S" , name:"超サイヤ人ゴッド 孫悟空" , color:"GRN" , tag:"サイヤ人" , tag:"孫一族" , tag:"神の気" , tag:"超サイヤ人ゴッド" } ,
    { id:59 , number:"DBL72-02S" , name:"アルティメット孫悟飯" , color:"PUR" , tag:"混血サイヤ人" , tag:"孫一族" } ,
    { id:60 , number:"DBL73-02S" , name:"超一星龍" , color:"GRN" , tag:"邪悪龍" , tag:"GT" , tag:"再生" , tag:"吸収" , tag:"合体戦士" , tag:"強大な敵" } ,
    { id:61 , number:"DBL74-03S" , name:"超サイヤ人 ブロリー" , color:"RED" , tag:"サイヤ人" , tag:"超サイヤ人" , tag:"強大な敵" } ,
    { id:62 , number:"DBL75-01S" , name:"孫悟空" , color:"YEL" , tag:"サイヤ人" , tag:"孫一族" } ,
    { id:63 , number:"DBL76-02S" , name:"超サイヤ人3 ゴテンクス" , color:"RED" , tag:"混血サイヤ人" , tag:"超サイヤ人3" , tag:"合体戦士" , tag:"フュージョン" , tag:"キッズ" } ,
    { id:64 , number:"DBL77-03S" , name:"ベジット" , color:"GRN" , tag:"サイヤ人" , tag:"未来" , tag:"合体戦士" , tag:"ポタラ" } ,
    { id:65 , number:"DBL77-05S" , name:"ゴクウブラック" , color:"YEL" , tag:"サイヤ人" , tag:"未来" , tag:"強大な敵" } ,
    { id:66 , number:"DBL-S" , name:"" , color:"" , tag:"" } ,
] ;